### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by felipeccastro** [ryanmorr/ready#1]
Nice job! I came to this project looking for a simpler alternative (and jquery-free) to https://github.com/AdamPietrasiak/jquery.initialize.

Your project seems perfect for it, though just like jquery.initialize, the browser support could be extended to IE9 by using a MutationObserver polyfill, wouldn't it?

**Comment by ryanmorr** [comment]
I would prefer to keep the lib small without any hacks or workarounds. Feel free to fork the project and add the functionality you desire.

**Comment by felipeccastro** [comment]
I know, I wasn't suggesting any hacks or code changes - just mentioning at the docs that adding a polyfill would make it work at IE9.

**Comment by ryanmorr** [comment]
Sorry for the confusion, I'll take it into consideration.
