### ISSUE TITLE
Unnecessary checks

### ISSUE THREAD

**Issue by felipeccastro** [ryanmorr/ready#2]
The check() function runs everytime I register a new selector.
I see that's needed to detect for elements already present at the page, but why do you need to run through all listeners, instead of just the selector being registered? Running through the other listeners seems to be unnecessary, and could have a noticeable perform impact as the listeners list grows.

**Comment by ryanmorr** [comment]
I made the change. Thanks for the heads up!

**Comment by felipeccastro** [comment]
You're welcome!
