### ISSUE TITLE
Any way to disconnect from a previously invoked ready()?

### ISSUE THREAD

**Issue by bengrosser** [ryanmorr/ready#3]
What the subject says. Since a ready() persists through lifetime of the page, I'm wondering if there's a way to disconnect/turn off a ready() after it's no longer needed. 

Thanks, appreciate the code!

**Comment by ryanmorr** [comment]
As it stands now, no there is not a way to disconnect the ready listener, sorry. 

I would suggest using a class name or data attribute unique to the element(s) that you are observing. Once the listener is dispatched for that particular selector, just ensure no other elements matching that selector are added to the DOM. That should give you the result you're looking for.

I will, however, leave this issue open as I consider adding this functionality.

**Comment by bengrosser** [comment]
Great, the unique ID was my thought too, though I wasn't sure whether there might be a perceptible cost to having an increasing number of open ready()'s—even if I know nothing else will emerge in the DOM to trigger them.

Another way to think about it would be to have a flag that makes a ready a one use only (e.g. finds first instance of the element, triggers the callback, and disconnects).

**Comment by ryanmorr** [comment]
I wouldn't worry about performance, only one mutation observer is used no matter how many times you open a ready listener. Although it's not ideal to have the mutation observer open when no more ready callbacks are expected.

I don't mind your suggestion, maybe something like `ready.once` for one offs would be an easy solution? I was also thinking `ready.off('.foo')` to explicitly remove a listener for a particular selector might be a good idea?

**Comment by bengrosser** [comment]
I see on the single observer; very nice. `ready.off('foo')` is probably more flexible, as it allows 1-n uses?

**Comment by ryanmorr** [comment]
Flexibility is what I had in mind. I like the idea of adding both the `once` and `off` functions rather than one or the other. 

I think i'll start working on it soon. Appreciate the input!

**Comment by bengrosser** [comment]
Of course! Thank you for the code. I had my own clunky MutationObserver going, but you made it elegant and simple to use.

**Comment by ryanmorr** [comment]
Made the change, it's not quite what we discussed here, instead I opted for a simpler solution. Now, the ready function returns a function that you can call to remove the listener. Refer to the updated readme for an example.

Thanks again.
